site_name: Numpy 教程
site_url: https://numpy.fengluoqiuwu.com
repo_url: https://github.com/fengluoqiuwu/numpy-tutorials
repo_name: numpy-tutorials

markdown_extensions:
  - attr_list

theme:
  name: material
  language: zh
  custom_dir: docs\overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.action.download
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      separator: '[\s\u200b\-]'

nav:
  - 引言: index.md
  - 1 Numpy介绍与安装: # 1-Numpy_installation/
    - 介绍: 1-Numpy_installation/index.md
    - Part 1. Python 的选择与安装: 1-Numpy_installation/1-Python.md
    - Part 2. Python 环境的配置: 1-Numpy_installation/2-Environment.md
    - Part 3. Numpy 安装与介绍: 1-Numpy_installation/3-Numpy.md
    - 视频讲座: 1-Numpy_installation/VideoLecture-1.md



extra_css:
  - stylesheets/custom.css
extra_javascript:
  - javascripts/extra.js


