name: Deploy site directory to server

on:
  push:
    branches:
      - master  # 当推送到 master 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 压缩 site 子目录
      - name: Archive site folder
        run: tar -czvf site.tar.gz ./site

      # 压缩 _sources 子目录
      - name: Archive _sources folder
        run: tar -czvf _sources.tar.gz ./_sources

      # 将压缩文件上传到服务器
      - name: Copy html files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: ./site.tar.gz
          target: /tmp/deployment/numpy

      # 将压缩文件上传到服务器
      - name: Copy sources files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: ./_sources.tar.gz
          target: /tmp/deployment/numpy

      # 在服务器上运行部署脚本
      - name: Run deploy script on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            bash /usr/local/bin/deploy.sh

